version: '2'
services:
  notebook:
    image: jupyter/tensorflow-notebook
    command:
     - start-notebook.sh
     - --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
    